"""Emit scripts/palette.tex with \\definecolor lines from the yeginbay palette.

palette.toml is the single color source for this repo's figures (see make_figures.py).
TikZ can't read TOML, so we generate the LaTeX color definitions from the installed
package instead of hardcoding hexes that could drift.

    uv run python scripts/gen_palette_tex.py
"""

from __future__ import annotations

from pathlib import Path

import yeginbay_palette as yp

# (LaTeX color name, palette group, palette key) — the six colors make_figures.py uses.
COLORS = [
    ("ink", "neutral", "ink"),
    ("paper", "neutral", "paper"),
    ("gray", "neutral", "gray"),
    ("graylight", "neutral", "gray_light"),
    ("primary", "accent", "primary"),
    ("secondary", "accent", "secondary"),
]


def main() -> None:
    palette = yp.apply_style()
    lines = ["% Generated by scripts/gen_palette_tex.py from yeginbay_palette/palette.toml.", "% Do not edit by hand; rerun the generator to refresh.", ""]
    for name, group, key in COLORS:
        hex_value = getattr(palette, group)(key).lstrip("#")
        lines.append(f"\\definecolor{{{name}}}{{HTML}}{{{hex_value.upper()}}}")
    out = Path(__file__).parent / "palette.tex"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
